### ISSUE TITLE
Release 4.0 sanity checklist

### ISSUE THREAD

**Issue by oxisto** [golang-jwt/jwt#69]
Anything else we are missing for 4.0?

- [x] No breaking changes - except Go version updates and changing the *contents* of error descriptions, but not the variables. Should we mention this somehow in the version guide?
- [x] Added static check for future PRs
- [x] Version history. Doesn't mention #44, but this is just internal to us anyway.

I would say, you are good to Go, @mfridman

Any last minute objections from anyone else, @Waterdrips, @lggomez, @ripienaar?

**Comment by lggomez** [comment]
From what I've seen on the migrated issues, one of the common issues people seem to have is trouble with documentation (I've brought some of them). It's not a pleaseant job but if not now at some time the docs will have to be improved a little bit

With respect to bugs, I think these 2 candidates would be a nice to have for the release #71 #75

**Comment by mfridman** [comment]
I'm going to release a `v4.0.0` tag now.
